/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.intlgds.amadeus.booking.endorse;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EndorseResponse implements org.apache.thrift.TBase<EndorseResponse, EndorseResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EndorseResponse");

  private static final org.apache.thrift.protocol.TField ORDER_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("orderNo", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CUSTOMER_ORDER_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("customerOrderNo", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ENDORSE_CS_ORDER_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("endorseCsOrderNo", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ENDORSE_ORDER_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("endorseOrderNo", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRUCT, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EndorseResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EndorseResponseTupleSchemeFactory());
  }

  public String orderNo; // required
  public String customerOrderNo; // required
  public String endorseCsOrderNo; // required
  public String endorseOrderNo; // required
  public com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable error; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ORDER_NO((short)1, "orderNo"),
    CUSTOMER_ORDER_NO((short)2, "customerOrderNo"),
    ENDORSE_CS_ORDER_NO((short)3, "endorseCsOrderNo"),
    ENDORSE_ORDER_NO((short)4, "endorseOrderNo"),
    ERROR((short)5, "error");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ORDER_NO
          return ORDER_NO;
        case 2: // CUSTOMER_ORDER_NO
          return CUSTOMER_ORDER_NO;
        case 3: // ENDORSE_CS_ORDER_NO
          return ENDORSE_CS_ORDER_NO;
        case 4: // ENDORSE_ORDER_NO
          return ENDORSE_ORDER_NO;
        case 5: // ERROR
          return ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.ERROR};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ORDER_NO, new org.apache.thrift.meta_data.FieldMetaData("orderNo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CUSTOMER_ORDER_NO, new org.apache.thrift.meta_data.FieldMetaData("customerOrderNo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENDORSE_CS_ORDER_NO, new org.apache.thrift.meta_data.FieldMetaData("endorseCsOrderNo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENDORSE_ORDER_NO, new org.apache.thrift.meta_data.FieldMetaData("endorseOrderNo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EndorseResponse.class, metaDataMap);
  }

  public EndorseResponse() {
  }

  public EndorseResponse(
    String orderNo,
    String customerOrderNo,
    String endorseCsOrderNo,
    String endorseOrderNo)
  {
    this();
    this.orderNo = orderNo;
    this.customerOrderNo = customerOrderNo;
    this.endorseCsOrderNo = endorseCsOrderNo;
    this.endorseOrderNo = endorseOrderNo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EndorseResponse(EndorseResponse other) {
    if (other.isSetOrderNo()) {
      this.orderNo = other.orderNo;
    }
    if (other.isSetCustomerOrderNo()) {
      this.customerOrderNo = other.customerOrderNo;
    }
    if (other.isSetEndorseCsOrderNo()) {
      this.endorseCsOrderNo = other.endorseCsOrderNo;
    }
    if (other.isSetEndorseOrderNo()) {
      this.endorseOrderNo = other.endorseOrderNo;
    }
    if (other.isSetError()) {
      this.error = new com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable(other.error);
    }
  }

  public EndorseResponse deepCopy() {
    return new EndorseResponse(this);
  }

  @Override
  public void clear() {
    this.orderNo = null;
    this.customerOrderNo = null;
    this.endorseCsOrderNo = null;
    this.endorseOrderNo = null;
    this.error = null;
  }

  public String getOrderNo() {
    return this.orderNo;
  }

  public EndorseResponse setOrderNo(String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

  public void unsetOrderNo() {
    this.orderNo = null;
  }

  /** Returns true if field orderNo is set (has been assigned a value) and false otherwise */
  public boolean isSetOrderNo() {
    return this.orderNo != null;
  }

  public void setOrderNoIsSet(boolean value) {
    if (!value) {
      this.orderNo = null;
    }
  }

  public String getCustomerOrderNo() {
    return this.customerOrderNo;
  }

  public EndorseResponse setCustomerOrderNo(String customerOrderNo) {
    this.customerOrderNo = customerOrderNo;
    return this;
  }

  public void unsetCustomerOrderNo() {
    this.customerOrderNo = null;
  }

  /** Returns true if field customerOrderNo is set (has been assigned a value) and false otherwise */
  public boolean isSetCustomerOrderNo() {
    return this.customerOrderNo != null;
  }

  public void setCustomerOrderNoIsSet(boolean value) {
    if (!value) {
      this.customerOrderNo = null;
    }
  }

  public String getEndorseCsOrderNo() {
    return this.endorseCsOrderNo;
  }

  public EndorseResponse setEndorseCsOrderNo(String endorseCsOrderNo) {
    this.endorseCsOrderNo = endorseCsOrderNo;
    return this;
  }

  public void unsetEndorseCsOrderNo() {
    this.endorseCsOrderNo = null;
  }

  /** Returns true if field endorseCsOrderNo is set (has been assigned a value) and false otherwise */
  public boolean isSetEndorseCsOrderNo() {
    return this.endorseCsOrderNo != null;
  }

  public void setEndorseCsOrderNoIsSet(boolean value) {
    if (!value) {
      this.endorseCsOrderNo = null;
    }
  }

  public String getEndorseOrderNo() {
    return this.endorseOrderNo;
  }

  public EndorseResponse setEndorseOrderNo(String endorseOrderNo) {
    this.endorseOrderNo = endorseOrderNo;
    return this;
  }

  public void unsetEndorseOrderNo() {
    this.endorseOrderNo = null;
  }

  /** Returns true if field endorseOrderNo is set (has been assigned a value) and false otherwise */
  public boolean isSetEndorseOrderNo() {
    return this.endorseOrderNo != null;
  }

  public void setEndorseOrderNoIsSet(boolean value) {
    if (!value) {
      this.endorseOrderNo = null;
    }
  }

  public com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable getError() {
    return this.error;
  }

  public EndorseResponse setError(com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ORDER_NO:
      if (value == null) {
        unsetOrderNo();
      } else {
        setOrderNo((String)value);
      }
      break;

    case CUSTOMER_ORDER_NO:
      if (value == null) {
        unsetCustomerOrderNo();
      } else {
        setCustomerOrderNo((String)value);
      }
      break;

    case ENDORSE_CS_ORDER_NO:
      if (value == null) {
        unsetEndorseCsOrderNo();
      } else {
        setEndorseCsOrderNo((String)value);
      }
      break;

    case ENDORSE_ORDER_NO:
      if (value == null) {
        unsetEndorseOrderNo();
      } else {
        setEndorseOrderNo((String)value);
      }
      break;

    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ORDER_NO:
      return getOrderNo();

    case CUSTOMER_ORDER_NO:
      return getCustomerOrderNo();

    case ENDORSE_CS_ORDER_NO:
      return getEndorseCsOrderNo();

    case ENDORSE_ORDER_NO:
      return getEndorseOrderNo();

    case ERROR:
      return getError();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ORDER_NO:
      return isSetOrderNo();
    case CUSTOMER_ORDER_NO:
      return isSetCustomerOrderNo();
    case ENDORSE_CS_ORDER_NO:
      return isSetEndorseCsOrderNo();
    case ENDORSE_ORDER_NO:
      return isSetEndorseOrderNo();
    case ERROR:
      return isSetError();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EndorseResponse)
      return this.equals((EndorseResponse)that);
    return false;
  }

  public boolean equals(EndorseResponse that) {
    if (that == null)
      return false;

    boolean this_present_orderNo = true && this.isSetOrderNo();
    boolean that_present_orderNo = true && that.isSetOrderNo();
    if (this_present_orderNo || that_present_orderNo) {
      if (!(this_present_orderNo && that_present_orderNo))
        return false;
      if (!this.orderNo.equals(that.orderNo))
        return false;
    }

    boolean this_present_customerOrderNo = true && this.isSetCustomerOrderNo();
    boolean that_present_customerOrderNo = true && that.isSetCustomerOrderNo();
    if (this_present_customerOrderNo || that_present_customerOrderNo) {
      if (!(this_present_customerOrderNo && that_present_customerOrderNo))
        return false;
      if (!this.customerOrderNo.equals(that.customerOrderNo))
        return false;
    }

    boolean this_present_endorseCsOrderNo = true && this.isSetEndorseCsOrderNo();
    boolean that_present_endorseCsOrderNo = true && that.isSetEndorseCsOrderNo();
    if (this_present_endorseCsOrderNo || that_present_endorseCsOrderNo) {
      if (!(this_present_endorseCsOrderNo && that_present_endorseCsOrderNo))
        return false;
      if (!this.endorseCsOrderNo.equals(that.endorseCsOrderNo))
        return false;
    }

    boolean this_present_endorseOrderNo = true && this.isSetEndorseOrderNo();
    boolean that_present_endorseOrderNo = true && that.isSetEndorseOrderNo();
    if (this_present_endorseOrderNo || that_present_endorseOrderNo) {
      if (!(this_present_endorseOrderNo && that_present_endorseOrderNo))
        return false;
      if (!this.endorseOrderNo.equals(that.endorseOrderNo))
        return false;
    }

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(EndorseResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    EndorseResponse typedOther = (EndorseResponse)other;

    lastComparison = Boolean.valueOf(isSetOrderNo()).compareTo(typedOther.isSetOrderNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrderNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orderNo, typedOther.orderNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCustomerOrderNo()).compareTo(typedOther.isSetCustomerOrderNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCustomerOrderNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.customerOrderNo, typedOther.customerOrderNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEndorseCsOrderNo()).compareTo(typedOther.isSetEndorseCsOrderNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndorseCsOrderNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endorseCsOrderNo, typedOther.endorseCsOrderNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEndorseOrderNo()).compareTo(typedOther.isSetEndorseOrderNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndorseOrderNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endorseOrderNo, typedOther.endorseOrderNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError()).compareTo(typedOther.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, typedOther.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EndorseResponse(");
    boolean first = true;

    sb.append("orderNo:");
    if (this.orderNo == null) {
      sb.append("null");
    } else {
      sb.append(this.orderNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("customerOrderNo:");
    if (this.customerOrderNo == null) {
      sb.append("null");
    } else {
      sb.append(this.customerOrderNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("endorseCsOrderNo:");
    if (this.endorseCsOrderNo == null) {
      sb.append("null");
    } else {
      sb.append(this.endorseCsOrderNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("endorseOrderNo:");
    if (this.endorseOrderNo == null) {
      sb.append("null");
    } else {
      sb.append(this.endorseOrderNo);
    }
    first = false;
    if (isSetError()) {
      if (!first) sb.append(", ");
      sb.append("error:");
      if (this.error == null) {
        sb.append("null");
      } else {
        sb.append(this.error);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (orderNo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'orderNo' was not present! Struct: " + toString());
    }
    if (customerOrderNo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'customerOrderNo' was not present! Struct: " + toString());
    }
    if (endorseCsOrderNo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'endorseCsOrderNo' was not present! Struct: " + toString());
    }
    if (endorseOrderNo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'endorseOrderNo' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (error != null) {
      error.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EndorseResponseStandardSchemeFactory implements SchemeFactory {
    public EndorseResponseStandardScheme getScheme() {
      return new EndorseResponseStandardScheme();
    }
  }

  private static class EndorseResponseStandardScheme extends StandardScheme<EndorseResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EndorseResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ORDER_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.orderNo = iprot.readString();
              struct.setOrderNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CUSTOMER_ORDER_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.customerOrderNo = iprot.readString();
              struct.setCustomerOrderNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENDORSE_CS_ORDER_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.endorseCsOrderNo = iprot.readString();
              struct.setEndorseCsOrderNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ENDORSE_ORDER_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.endorseOrderNo = iprot.readString();
              struct.setEndorseOrderNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.error = new com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable();
              struct.error.read(iprot);
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EndorseResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.orderNo != null) {
        oprot.writeFieldBegin(ORDER_NO_FIELD_DESC);
        oprot.writeString(struct.orderNo);
        oprot.writeFieldEnd();
      }
      if (struct.customerOrderNo != null) {
        oprot.writeFieldBegin(CUSTOMER_ORDER_NO_FIELD_DESC);
        oprot.writeString(struct.customerOrderNo);
        oprot.writeFieldEnd();
      }
      if (struct.endorseCsOrderNo != null) {
        oprot.writeFieldBegin(ENDORSE_CS_ORDER_NO_FIELD_DESC);
        oprot.writeString(struct.endorseCsOrderNo);
        oprot.writeFieldEnd();
      }
      if (struct.endorseOrderNo != null) {
        oprot.writeFieldBegin(ENDORSE_ORDER_NO_FIELD_DESC);
        oprot.writeString(struct.endorseOrderNo);
        oprot.writeFieldEnd();
      }
      if (struct.error != null) {
        if (struct.isSetError()) {
          oprot.writeFieldBegin(ERROR_FIELD_DESC);
          struct.error.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EndorseResponseTupleSchemeFactory implements SchemeFactory {
    public EndorseResponseTupleScheme getScheme() {
      return new EndorseResponseTupleScheme();
    }
  }

  private static class EndorseResponseTupleScheme extends TupleScheme<EndorseResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EndorseResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.orderNo);
      oprot.writeString(struct.customerOrderNo);
      oprot.writeString(struct.endorseCsOrderNo);
      oprot.writeString(struct.endorseOrderNo);
      BitSet optionals = new BitSet();
      if (struct.isSetError()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetError()) {
        struct.error.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EndorseResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.orderNo = iprot.readString();
      struct.setOrderNoIsSet(true);
      struct.customerOrderNo = iprot.readString();
      struct.setCustomerOrderNoIsSet(true);
      struct.endorseCsOrderNo = iprot.readString();
      struct.setEndorseCsOrderNoIsSet(true);
      struct.endorseOrderNo = iprot.readString();
      struct.setEndorseOrderNoIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.error = new com.intlgds.amadeus.booking.error.AmadeusBookingErrorTable();
        struct.error.read(iprot);
        struct.setErrorIsSet(true);
      }
    }
  }

}

